GA4:
  outputs:
    dev:
      dataset: dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /users/Samuel/dbttest-435106-3b9420ea6257.json
      location: US
      method: service-account
      priority: interactive
      project: dbttest-435106
      threads: 4
      type: bigquery
    prod:
      dataset: prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /users/Samuel/dbttest-435106-3b9420ea6257.json
      location: US
      method: service-account
      priority: interactive
      project: dbttest-435106
      threads: 4
      type: bigquery
    slim_ci:
      dataset: slim_ci
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /users/Samuel/dbttest-435106-3b9420ea6257.json
      location: US
      method: service-account
      priority: interactive
      project: dbttest-435106
      threads: 4
      type: bigquery
  target: dev
